### ISSUE TITLE
Divide by 0 err in _includes/archive-single.html

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/jekyll-theme-unit-test#1]
After I copied the contents of jekyll-theme-unit-test into a clone of minimal-mistakes and bundle'd,
running bundle exec jekyll serve yielded this error message:

```
Configuration file: /Users/mac/gits/jekyll/minimal-mistakes/_config.yml
            Source: /Users/mac/gits/jekyll/minimal-mistakes
       Destination: /Users/mac/gits/jekyll/minimal-mistakes/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: divided by 0 in _includes/archive-single.html, included in page6/index.html
jekyll 3.0.3 | Error:  divided by 0

```

**Comment by mmistakes** [comment]
Try `bundle exec jekyll build --trace --verbose` to see what file its choking on. My guess is you have pagination on as the message above references `page6/index.html` which is something the `jekyll-paginate` plugin outputs.

**Comment by wilsonmar** [comment]
Attached is the output from bundle exec jekyll build --trace --verbose.
I don't see a **page6** folder in either minimal-mistakes nor jekyll-theme-unit-test.
And I don't see a reference to "page" within _includes/archive-single.html before Liquid has its way.
But there is a page6 folder within minimal-mistakes-demo's _site folder.

**Comment by mmistakes** [comment]
You found a bug with the theme. I mistakenly commented out `words_per_minute: 200` in `_config.yml` which was causing the a ["reading time" test post](https://github.com/mmistakes/jekyll-theme-unit-test/blob/master/_posts/2012-01-02-layout-read-time.md) to fail since the condition to enable it was looking for a variable that didn't exist.

The `page6` folder is part of jekyll-paginate. It's creating pages for the homepage that paginates every 5 posts.

**Comment by mmistakes** [comment]
Fixed upstream.
